{% set name = "actions-toolkit" %}
{% set version = "0.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/actions-toolkit-{{ version }}.tar.gz
  sha256: 49615a8bc6941fdaa374f82cfb19432379b59bcae0d2a99bf8b80d704a64091e

build:
  noarch: python
  script:
    - rm -rf tests  # [not win]
    - rd /s /q tests  # [win]
    - {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - pygithub

test:
  imports:
    - actions_toolkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yanglbme/actions-toolkit
  summary: 🛠 The GitHub ToolKit for developing GitHub Actions in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
